export { EditorView } from "@codemirror/view";
export { ConfigEditor, type ConfigEditorProps } from "./components/ConfigEditor";
export { GcodeEditor, type GcodeEditorProps } from "./components/GcodeEditor";
export { JsonViewer, type JsonViewerProps } from "./components/JsonViewer";
export { KlipperConfigViewer, type KlipperConfigViewerProps } from "./components/KlipperConfigViewer";
export { ValidationStatusPopup } from "./components/ValidationStatusPopup";
export { EditorScrollProvider, useEditorScroll } from "./context/editor-scroll-context";
export { defaultMatchExtension, dispatchDefaultMatches } from "./extensions/default-match-extension";
export { diffExtension, dispatchDiffLines } from "./extensions/diff-extension";
export { editorTheme } from "./extensions/editor-theme";
export { dispatchFieldHints, type FieldHint, fieldHintExtension } from "./extensions/field-hint-extension";
export { flashLineEffect, flashLineExtension } from "./extensions/flash-line-extension";
export { klipperFoldService } from "./extensions/fold-extension";
export type { InlineEditRequest } from "./extensions/inline-edit-extension";
export { klipperLanguage } from "./extensions/klipper-language";
export { dispatchOverrides, overrideExtension } from "./extensions/override-extension";
export { dispatchUnmanagedSections, unmanagedExtension } from "./extensions/unmanaged-extension";
export { dispatchDiagnostics, validationExtension } from "./extensions/validation-extension";
export { computeChangedLines } from "./utils/line-diff";
