import { describe, expect, it } from "vitest";
import { createDefaultRegistry } from "../../sections/schemas";
import { serializeMultiFileConfig } from "../../sections/serializer";
import type { ConfigDocument } from "../../sections/types";

describe("serializeMultiFileConfig", () => {
  const registry = createDefaultRegistry();

  it("produces single file when no files array", () => {
    const doc: ConfigDocument = {
      sections: [
        {
          definitionId: "printer",
          data: { kinematics: "corexy", max_velocity: 300, max_accel: 3000 },
        },
      ],
    };

    const result = serializeMultiFileConfig(doc, registry);
    expect(result.files.size).toBe(1);
    expect(result.files.has("printer.cfg")).toBe(true);
    expect(result.files.get("printer.cfg")).toContain("[printer]");
    expect(result.sourceMaps.has("printer.cfg")).toBe(true);
  });

  it("splits sections into separate files based on file field", () => {
    const doc: ConfigDocument = {
      sections: [
        { definitionId: "include", instanceName: "fans.cfg", data: {} },
        {
          definitionId: "printer",
          data: { kinematics: "corexy", max_velocity: 300, max_accel: 3000 },
        },
        {
          definitionId: "fan",
          data: { pin: "PA8" },
          file: "fans.cfg",
        },
      ],
      files: ["printer.cfg", "fans.cfg"],
    };

    const result = serializeMultiFileConfig(doc, registry);
    expect(result.files.size).toBe(2);

    const mainContent = result.files.get("printer.cfg");
    expect(mainContent).toContain("[printer]");
    expect(mainContent).toContain("[include fans.cfg]");
    expect(mainContent).not.toContain("[fan]");

    const fansContent = result.files.get("fans.cfg");
    expect(fansContent).toContain("[fan]");
    expect(fansContent).toContain("pin: PA8");
    expect(fansContent).not.toContain("[printer]");
  });

  it("serializes [include] sections from document sections", () => {
    const doc: ConfigDocument = {
      sections: [
        { definitionId: "include", instanceName: "fans.cfg", data: {} },
        { definitionId: "include", instanceName: "extruder.cfg", data: {} },
        {
          definitionId: "printer",
          data: { kinematics: "cartesian", max_velocity: 200, max_accel: 2000 },
        },
        {
          definitionId: "fan",
          data: { pin: "PA8" },
          file: "fans.cfg",
        },
        {
          definitionId: "extruder",
          data: {
            step_pin: "PE2",
            dir_pin: "PE3",
            enable_pin: "!PD4",
            microsteps: 16,
            rotation_distance: 33.5,
            nozzle_diameter: 0.4,
            filament_diameter: 1.75,
            heater_pin: "PA1",
            sensor_type: "EPCOS 100K B57560G104F",
            sensor_pin: "PF3",
            min_temp: 0,
            max_temp: 260,
          },
          file: "extruder.cfg",
        },
      ],
      files: ["printer.cfg", "fans.cfg", "extruder.cfg"],
    };

    const result = serializeMultiFileConfig(doc, registry);
    const mainContent = result.files.get("printer.cfg");
    expect(mainContent).toContain("[include fans.cfg]");
    expect(mainContent).toContain("[include extruder.cfg]");
  });

  it("puts header only on main file", () => {
    const doc: ConfigDocument = {
      sections: [
        { definitionId: "include", instanceName: "fans.cfg", data: {} },
        {
          definitionId: "printer",
          data: { kinematics: "corexy", max_velocity: 300, max_accel: 3000 },
        },
        {
          definitionId: "fan",
          data: { pin: "PA8" },
          file: "fans.cfg",
        },
      ],
      files: ["printer.cfg", "fans.cfg"],
    };

    const header = "# Generated by KlipperForge";
    const result = serializeMultiFileConfig(doc, registry, { header });

    expect(result.files.get("printer.cfg")).toContain(header);
    expect(result.files.get("fans.cfg")).not.toContain(header);
  });

  it("puts rawSections and saveConfigSections only in main file", () => {
    const doc: ConfigDocument = {
      sections: [
        { definitionId: "include", instanceName: "fans.cfg", data: {} },
        {
          definitionId: "printer",
          data: { kinematics: "corexy", max_velocity: 300, max_accel: 3000 },
        },
        {
          definitionId: "fan",
          data: { pin: "PA8" },
          file: "fans.cfg",
        },
      ],
      files: ["printer.cfg", "fans.cfg"],
      rawSections: ["[gcode_macro START]\ngcode:\n  G28"],
      saveConfigSections: [{ type: "bed_mesh", name: "default", values: { version: 1 } }],
    };

    const result = serializeMultiFileConfig(doc, registry);
    const mainContent = result.files.get("printer.cfg");
    const fansContent = result.files.get("fans.cfg");

    expect(mainContent).toContain("gcode_macro START");
    expect(mainContent).toContain("SAVE_CONFIG");
    expect(fansContent).not.toContain("gcode_macro");
    expect(fansContent).not.toContain("SAVE_CONFIG");
  });

  it("includes source map entries for include sections", () => {
    const doc: ConfigDocument = {
      sections: [
        { definitionId: "include", instanceName: "fans.cfg", data: {} },
        {
          definitionId: "printer",
          data: { kinematics: "corexy", max_velocity: 300, max_accel: 3000 },
        },
        {
          definitionId: "fan",
          data: { pin: "PA8" },
          file: "fans.cfg",
        },
      ],
      files: ["printer.cfg", "fans.cfg"],
    };

    const result = serializeMultiFileConfig(doc, registry);
    const mainMap = result.sourceMaps.get("printer.cfg");
    const fansMap = result.sourceMaps.get("fans.cfg");

    // Include and printer sections should have source map entries
    expect(mainMap?.sectionLines.get("include fans.cfg")).toBeGreaterThan(0);
    expect(mainMap?.sectionLines.get("printer")).toBeGreaterThan(0);

    // Fans file should have normal line numbers
    expect(fansMap?.sectionLines.get("fan")).toBe(1);
  });
});
