import { describe, expect, it } from "vitest";
import { cfgToDocument } from "../import.js";
import { parseKlipperConfig } from "../parser.js";
import { createDefaultRegistry } from "../sections/schemas/index.js";
import { serializeConfig } from "../sections/serializer.js";
import type { ConfigDocument } from "../sections/types.js";

describe("board-aliases round-trip", () => {
  const registry = createDefaultRegistry();
  const headerOptions = { header: "# Generated by KlipperForge" };

  it("serializes _boardSource as annotation in header block", () => {
    const doc: ConfigDocument = {
      sections: [
        {
          definitionId: "board_pins",
          data: {
            aliases: "FAN0=PA8, FAN1=PE5",
          },
          meta: { _boardSource: "btt-octopus-pro-1.1" },
        },
      ],
    };
    const output = serializeConfig(doc, registry, headerOptions);
    expect(output).toContain("# klipperforge:[board_pins]:board-aliases:btt-octopus-pro-1.1");
    expect(output).toContain("[board_pins]\n");
    expect(output).not.toContain("[board_pins] #");
    expect(output).toContain("aliases: FAN0=PA8, FAN1=PE5");
  });

  it("serializes named board_pins with _boardSource in header block", () => {
    const doc: ConfigDocument = {
      sections: [
        {
          definitionId: "board_pins_named",
          instanceName: "mcu2",
          data: {
            mcu: "mcu2",
            aliases: "FAN0=PA8",
          },
          meta: { _boardSource: "btt-octopus-pro-1.1" },
        },
      ],
    };
    const output = serializeConfig(doc, registry, headerOptions);
    expect(output).toContain("# klipperforge:[board_pins mcu2]:board-aliases:btt-octopus-pro-1.1");
    expect(output).not.toContain("[board_pins mcu2] #");
  });

  it("does not emit board-aliases comment without meta", () => {
    const doc: ConfigDocument = {
      sections: [
        {
          definitionId: "board_pins",
          data: {
            aliases: "FAN0=PA8",
          },
        },
      ],
    };
    const output = serializeConfig(doc, registry);
    expect(output).toContain("[board_pins]");
    expect(output).not.toContain("klipperforge:");
  });

  it("round-trips board-aliases annotation through parse → import → serialize (new format)", () => {
    const input = `# klipperforge:[board_pins]:board-aliases:btt-octopus-pro-1.1

[board_pins]
aliases:
  FAN0=PA8, FAN1=PE5`;

    const parsed = parseKlipperConfig(input, { extended: true });
    const doc = cfgToDocument(parsed.sections, parsed.mcuBoards, registry, parsed.saveConfigSections);

    expect(doc.sections).toHaveLength(1);
    expect(doc.sections[0].meta?._boardSource).toBe("btt-octopus-pro-1.1");

    const output = serializeConfig(doc, registry, headerOptions);
    expect(output).toContain("# klipperforge:[board_pins]:board-aliases:btt-octopus-pro-1.1");
    expect(output).not.toContain("[board_pins] #");
  });

  it("round-trips legacy inline board-aliases annotation", () => {
    const input = `[board_pins] # klipperforge:board-aliases:btt-octopus-pro-1.1
aliases:
  FAN0=PA8, FAN1=PE5`;

    const parsed = parseKlipperConfig(input, { extended: true });
    const doc = cfgToDocument(parsed.sections, parsed.mcuBoards, registry, parsed.saveConfigSections);

    expect(doc.sections).toHaveLength(1);
    expect(doc.sections[0].meta?._boardSource).toBe("btt-octopus-pro-1.1");

    const output = serializeConfig(doc, registry, headerOptions);
    expect(output).toContain("# klipperforge:[board_pins]:board-aliases:btt-octopus-pro-1.1");
  });

  it("does not set _boardSource for non-board-aliases annotations", () => {
    const input = `# klipperforge:[mcu]:btt-octopus-pro-1.1

[mcu]
serial: /dev/serial/by-id/test`;

    const parsed = parseKlipperConfig(input, { extended: true });
    const doc = cfgToDocument(parsed.sections, parsed.mcuBoards, registry, parsed.saveConfigSections);

    expect(doc.sections[0].meta).toBeUndefined();
  });

  it("preserves user-created board_pins without annotation", () => {
    const input = `[board_pins]
aliases:
  MY_CUSTOM=PA0`;

    const parsed = parseKlipperConfig(input, { extended: true });
    const doc = cfgToDocument(parsed.sections, parsed.mcuBoards, registry, parsed.saveConfigSections);

    expect(doc.sections).toHaveLength(1);
    expect(doc.sections[0].meta).toBeUndefined();
  });
});
